# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c6qA5E85DCut8yemaUmF5qLRqKid4dUa
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Your data
data = {
    'country': ['France', 'Mexico', 'United States', 'Italy', 'Hungary', 'Croatia', 'Turkey', 'Austria', 'Germany', 'Virgin Islands', 'United Arab Emirates', 'Greece', 'Netherlands', 'Russia'],
    'tourists_in_millions': [117.1, 51.1, 45, 38.4, 31.6, 21.6, 16, 15.1, 12.4, 8.6, 8.1, 7.4, 7.3, 6.4],
    'receipts_in_billions': [35.96, 11.45, 84.21, 20.46, 4.22, 5.63, 13.77, 15.36, 58.37, 0.69, 24.62, 6.19, 10.93, 4.96],
    'receipts_per_tourist': [307, 224, 1870, 533, 133, 261, 862, 1018, 4689, 80, 3045, 836, 1504, 780],
    'percentage_of_gdp': [1.2, 0.9, 0.4, 1, 2.3, 8.3, 1.7, 3.2, 1.4, 16.3, 6.9, 2.9, 1.1, 0.3]
}

df = pd.DataFrame(data)

# Display the DataFrame
df


# Summary statistics
summary_stats = df.describe()

# Display summary statistics
summary_stats



# Set the style for the plots with a light gray background
sns.set(style="whitegrid", rc={"axes.facecolor": "#f0f0f0", "grid.color": "#ffffff"})

# Plot 1: Bar plot for Tourists in Millions
plt.figure(figsize=(12, 6))
sns.barplot(x='country', y='tourists_in_millions', data=df, palette='viridis')
plt.title('Tourists in Millions by Country')
plt.xlabel('Country')
plt.ylabel('Tourists in Millions')
plt.xticks(rotation=45)
plt.show()

# Plotting a balanced Donut chart for Percentage of GDP
plt.figure(figsize=(10, 10))
explode = [0.05] * len(df_subset)  # Slight separation between slices

# Plotting the pie chart with a circular layout
wedges, texts, autotexts = plt.pie(df_subset['percentage_of_gdp'], labels=df_subset['country'], autopct='%1.1f%%',
                                    startangle=90, colors=sns.color_palette('pastel'), wedgeprops=dict(width=0.4),
                                    explode=explode, pctdistance=0.85, counterclock=False)

# Drawing a circle in the center to create a donut chart
centre_circle = plt.Circle((0, 0), 0.70, fc='white')
fig = plt.gcf()
fig.gca().add_artist(centre_circle)

# Adding labels and adjusting layout
plt.title('Percentage of GDP from Tourism (Top 10 Countries)')
plt.setp(autotexts, size=8, weight="bold", color="white")  # Adjusting the label size and color
plt.axis('equal')  # Equal aspect ratio ensures that the pie chart is circular
plt.show()



# Plot 3: Horizontal bar plot for Receipts per Tourist
plt.figure(figsize=(12, 6))
sns.barplot(x='receipts_per_tourist', y='country', data=df, palette='rocket')
plt.title('Receipts per Tourist by Country')
plt.xlabel('Receipts per Tourist')
plt.ylabel('Country')
plt.show()

# Plot 4: Trend plot for Receipts in Billions
plt.figure(figsize=(12, 6))
sns.lineplot(x='country', y='receipts_in_billions', data=df, marker='o', color='orange')
plt.title('Receipts in Billions by Country')
plt.xlabel('Country')
plt.ylabel('Receipts in Billions')
plt.xticks(rotation=45)
plt.show()